### PR TITLE
Fix container entrypoint and commands

### LINKED ISSUE #216: Can't run pod: No command specified
```
$ hyper run --rm gcr.io/google_containers/etcd:2.0.9 /usr/local/bin/etcd
hyper ERROR: Error from daemon's response: No command specified
```

### PR DESCRIPTION
**Pull request by feiskyer**
Fix #216

### CODE REVIEW

File: daemon/pod.go [hunk 1]
```diff
@@ -195,6 +196,8 @@ func (p *Pod) InitContainers(daemon *Daemon) error {
 
 		config := &container.Config{
 			Image:           c.Image,
+			Entrypoint:      strslice.New(c.Entrypoint...),
```
Comment (gao-feng) [inline daemon/pod.go]: I saw  the pr https://github.com/hyperhq/hyper/pull/201 check the entrypoint before assign it to config.Entrypoint

+               if len(c.Entrypoint) != 0 {
+                       config.Entrypoint = strslice.New(c.Entrypoint...)
                }
